### ISSUE TITLE
Does this project work?

### ISSUE THREAD

**Issue by jfacorro** [falood/exsync#1]
I couldn't get it to reload any files after adding it as a dependency and starting the `:exsync` application. Are there any further steps needed to have the modules reloaded when the source file changes?

**Comment by falood** [comment]
It just work fine under OSX system and depends on `fswatch` command.
BUT I found this project (https://github.com/synrc/fs)[https://github.com/synrc/fs] and I'll instead `fswatch` by the project.
I'll make `exsync` work fine next version.

Thank you.

**Comment by jfacorro** [comment]
Cool, thanks for the reply!
