### ISSUE TITLE
No reloading of external resources

### ISSUE THREAD

**Issue by CrowdHailer** [falood/exsync#10]
I have a module which relies on external file.
This external file is declared as a resource.
When I change this external resource the module does not recompile.
Is it possible to get these changes picked up by exsync?

```elixir
require EEx

@external_resource Path.join(__DIR__, "./templates/home_page.html.eex")
EEx.function_from_file(:defp, :home_page, Path.join(__DIR__, "./templates/home_page.html.eex"), [:greeting])
```

**Comment by falood** [comment]
@CrowdHailer 
I'm really really sorry, I missed this issue and saw it until I get a pr recently. just added `addition_dirs` config for `exsync`, I think will work for you.

**Comment by CrowdHailer** [comment]
No worries. I think this should work

I would still vote for making use of the `@external_resource` attribute so configuration does not have to stay in sync through the codebase

**Comment by falood** [comment]
will keep it in my mind 🙂 thank you for your suggestion
