### ISSUE TITLE
Errors are swallowed during recompilation

### ISSUE THREAD

**Issue by CrowdHailer** [falood/exsync#14]
I have a routing DSL that deliberately throws errors during the compilation step if controllers are not defined correctly. The error messages are very useful and are shown if manually calling recompile.

e.g. 
```
iex(1)> recompile
Compiling 1 file (.ex)

== Compilation error in file lib/www.ex ==
** (RuntimeError) module WWW.HomePagezz is not loaded
    (raxx) lib/raxx/router.ex:51: anonymous fn/3 in Raxx.Router."MACRO-__using__"/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (raxx) expanding macro: Raxx.Router.__using__/1
    lib/www.ex:9: WWW (module)
    (elixir) expanding macro: Kernel.use/2
    lib/www.ex:9: WWW (module)
    (tokumei) expanding macro: Raxx.Blueprint.__using__/1
    lib/www.ex:9: WWW (module)
```

When using ExSync. There is simply no output if recompilation fails. Is there a configuration that allows me to show the same errors as I would get for calling recompile.

**Comment by falood** [comment]
I will check why it's missed 🙂  thanks

**Comment by lATAl** [comment]
Hi @falood, any updates for this issue?

**Comment by axelson** [comment]
@CrowdHailer this is improved with #33. Please try it out on the master branch.
