### ISSUE TITLE
Disable logger

### ISSUE THREAD

**Issue by sobolevn** [falood/exsync#24]
Thanks! Awesome project, really helps me to develop inside my `iex` shell.

But, these logs are spamming my `iex`:

```
[debug] Defaulting to enable source monitor, set config :exsync, src_monitor: false to disable
[info] ExSync source monitor started.
[info] ExSync beam monitor started.
```

Can you please make a setting to disable them?

**Comment by axelson** [comment]
This is now fixed with #32! You can either disable the logs completely or add a snippet to your `.iex.exs` that will stop the ExSync logs from overwriting your prompt. Try it out on the master branch.
