### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by axelson** [falood/exsync#25]
Is it possible to push a new release with all the latest improvements? I mainly want the MFA callback

**Comment by axelson** [comment]
@falood any chance to look at this?

**Comment by falood** [comment]
Hi @axelson, the new version released, thanks so much about your help for this project, do you mind I invite you as a contributor to this project?

**Comment by axelson** [comment]
You're welcome! And yeah that would be great. I'm https://hex.pm/users/axelson on hex.pm
