### ISSUE TITLE
Problems running exsync on umbrella projects

### ISSUE THREAD

**Issue by lucca65** [falood/exsync#3]
Hi!

I can't make exsync to work on my project. I'm using an umbrella to hold all of our projects together, and the only working situation is on one of the projects. Tried to make it work on each one of the three projects by referencing exsync on them, but that didn't worked as well...

Is umbrella projects supported?

**Comment by falood** [comment]
Thank you for point it out!
But I can't find any other way to start `:exsync` when start umbrella project except stared it as `Mix.Task`.
Leave me a line or take pull request if you have a better idea!
