### ISSUE TITLE
ExSync is working but `register_group_leader` errors

### ISSUE THREAD

**Issue by formido** [falood/exsync#40]
ExSync is working fine for reloading code. But not overwriting the prompt would be nice, so when I try this:

```elixir
iex(3)> ExSync.register_group_leader()
** (UndefinedFunctionError) function ExSync.register_group_leader/0 is undefined or private
    (exsync 0.2.4) ExSync.register_group_leader()
```

**Comment by axelson** [comment]
@formido `register_group_leader` is currently only on master and hasn't made it into a release yet. If you could test master that would be very helpful to me.

**Comment by formido** [comment]
It works! It's not wiping out the prompt and also I'm getting logs after both successful and unsuccessful compiles, which I wasn't before. Thanks!

**Comment by axelson** [comment]
That's great, thanks for checking!
