### ISSUE TITLE
Saving file in Panic Nova doesn't trigger reload

### ISSUE THREAD

**Issue by formido** [falood/exsync#41]
When I save a file in Panic Nova, code reloading doesn't occur. No messages appear in the console and also if I add functions and try to call them, they don't exist.

If I open the same file in emacs and make those changes, everything works as expected.

Can editors bypass the fileystem notifications or intercept them for their own purposes?

**Comment by formido** [comment]
Actually, ExSync doesn't pick up changes with TextEdit either. Do Cocoa file writing APIs bypass the filesytem watcher, I wonder?

I notice that Nova's code windows immediately reflect updates if I edit a file outside of it in emacs or TextEdit, but they may be using Mac-specific APIs for filesytem change notifications.

**Comment by falood** [comment]
Hey @formido 
I don't think there's a specific API for Panic Nova to save a file without notifying the system.
but we have another backend called `:fs_poll`, you can enable it by adding such code to your config.ex

```elixir
config :file_system, backend: :fs_pool
```

can you give it a try?

**Comment by formido** [comment]
It worked! Thanks.

ExSync is way better for me than other reloaders I've tried, like the one in Phoenix. Being able to auto reload deps is a must for my workflow. 🚀 💯
