### ISSUE TITLE
Change primary branch to main

### ISSUE THREAD

**Issue by axelson** [falood/exsync#48]
@falood can we change the default branch of this repo to `main` to match many other repos (and the new default)? I don't have the permissions on this repo to make that change.

**Comment by falood** [comment]
done.

I just checked the permission, there's no option to assigned you as an admin for this repo.

btw, I just got a full time elixir developer role, I think I can spend more time on elixir projects. I'll pay more attention on the tickets/issues, but feel free to keep maintaining this project as an owner, and we can create a new organization for that if you want.

Thanks

**Comment by axelson** [comment]
Thanks and Congratulations on the new job! I think creating an organization would be great 👍
