### ISSUE TITLE
No recompilation errors

### ISSUE THREAD

**Issue by SerikDM** [falood/exsync#52]
Hello!
I'm using it for umbrella app and don't see any recompilation errors in output. The only message I get is about reload is complete.

**Comment by axelson** [comment]
This should be fixed in v0.3.0. Can you please check again and let me know if that fixes it for you? In the meantime I'm going to close this issue.

Also keep in mind that the umbrella instructions changed in 0.3.0. See https://github.com/falood/exsync/pull/47 for details.
