### ISSUE TITLE
Remove dev environment validation

### ISSUE THREAD

**Issue by emedinag** [falood/exsync#60]
Hi, an user can have multiple dev environments, and the decision could be in the mix.exs file ,

https://github.com/falood/exsync/blame/ffabe499f85cf19ab13af91937f5f9677f3c62b6/lib/exsync/application.ex#L10

Other option can be 

```    
case Mix.env() do
      :pdn ->
         Logger.error("ExSync NOT started. Non`:pdn` environment is supported.")
        {:ok, self()}
      _ ->
        start_supervisor()
    end
```

**Comment by axelson** [comment]
Yeah that makes sense. In 368cbcc30a30278e179059ccedb84c8a261bd5c1 I've removed the `Mix.env` check. In the readme we still recommend only installing exsync for the dev environment so there's still _some_ guardrails against running this in production by accident. Thanks for the suggestion!
